// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFHLMSuOYrZhOhW9pgSrkJxIBFcbxqlIA',
    appId: '1:143435670432:web:44dd89a44281c8ce8bfac5',
    messagingSenderId: '143435670432',
    projectId: 'final-self-app-project',
    authDomain: 'final-self-app-project.firebaseapp.com',
    storageBucket: 'final-self-app-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-FsjTcPXAD-VF7_56GhOE5KPMJ0yH5m8',
    appId: '1:143435670432:android:ae1d65cf4cac377f8bfac5',
    messagingSenderId: '143435670432',
    projectId: 'final-self-app-project',
    storageBucket: 'final-self-app-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA931LwAIAr2tF3GSaYvpUjoNxwP8fKnu0',
    appId: '1:143435670432:ios:3ffb739c9de8ce648bfac5',
    messagingSenderId: '143435670432',
    projectId: 'final-self-app-project',
    storageBucket: 'final-self-app-project.firebasestorage.app',
    iosClientId: '143435670432-uun20ht5r5kk8kpl6m55n4hh8jsbmsc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdc100Series',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA931LwAIAr2tF3GSaYvpUjoNxwP8fKnu0',
    appId: '1:143435670432:ios:3ffb739c9de8ce648bfac5',
    messagingSenderId: '143435670432',
    projectId: 'final-self-app-project',
    storageBucket: 'final-self-app-project.firebasestorage.app',
    iosClientId: '143435670432-uun20ht5r5kk8kpl6m55n4hh8jsbmsc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdc100Series',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFHLMSuOYrZhOhW9pgSrkJxIBFcbxqlIA',
    appId: '1:143435670432:web:07e7691c125f99cf8bfac5',
    messagingSenderId: '143435670432',
    projectId: 'final-self-app-project',
    authDomain: 'final-self-app-project.firebaseapp.com',
    storageBucket: 'final-self-app-project.firebasestorage.app',
  );
}
